/**
 * chopsticksAI — LLM-backed assistant for Chopsticks HQ.
 *
 *   POST /api/chopsticks-ai  { messages: [{role, content}, ...] }
 *        -> { reply, mode: "live" | "unconfigured" | "limited" }
 *
 * The OpenRouter key comes from env (OPENROUTER_API_KEY) and is only ever used
 * here, server-side. It is never shipped to a browser or embedded in the app —
 * an OpenRouter key is account-scoped, not model-scoped, so a leaked one can be
 * spent on paid models regardless of which model this endpoint requests.
 *
 * Answers are grounded in the generated knowledge base: the most relevant
 * entries are retrieved and injected as context so the model quotes real
 * version numbers and install commands instead of inventing them.
 */
// Verify the exact slug at https://openrouter.ai/models - OpenRouter model ids
// change between releases, and a wrong one fails the request with a 404.
const MODEL = process.env.CHOPSTICKS_AI_MODEL || "nvidia/nemotron-3-super-120b-a12b:free";
const OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions";
const TIMEOUT_MS = 25000;

// Context window of the model, minus headroom for the reply.
const MAX_CONTEXT_TOKENS = Number(process.env.CHOPSTICKS_AI_MAX_CONTEXT || 48000);
const MAX_REPLY_TOKENS = 400;

const MAX_MESSAGES = 12;        // trailing turns kept from the client
const MAX_CHARS_PER_MSG = 2000;
const GROUNDING_INTENTS = 6;

// Free-tier budget: once TOKEN_BUDGET is spent the endpoint stops calling the
// model for COOLDOWN_MS, so a burst of traffic cannot burn the whole allowance
// and leave the assistant dead for everyone.
const TOKEN_BUDGET = Number(process.env.CHOPSTICKS_AI_TOKEN_BUDGET || 750000);
const COOLDOWN_MS = Number(process.env.CHOPSTICKS_AI_COOLDOWN_MS || 3 * 60 * 60 * 1000);
const budget = { used: 0, windowStart: Date.now(), cooldownUntil: 0 };

// Simple in-memory throttle. Serverless instances are short-lived so this is a
// speed bump against casual abuse, not a guarantee; it costs nothing and stops
// a single tab hammering the endpoint.
const RATE_WINDOW_MS = 60000;
const RATE_MAX = 20;
const hits = new Map();

/** ~4 chars per token, deliberately an over-estimate so trimming fires early
 *  rather than letting OpenRouter reject an oversized request. */
const estimateTokens = (text) => Math.max(1, Math.ceil(String(text || "").length / 4));
const messageTokens = (m) => estimateTokens(m.content) + 4;

/** Drops the oldest turns until system prompt + history fits the window. The
 *  system prompt is never trimmed - it carries the grounding facts. */
function fitContext(system, turns) {
  const budgetTokens = MAX_CONTEXT_TOKENS - MAX_REPLY_TOKENS - messageTokens(system);
  const kept = [];
  let used = 0;
  for (let i = turns.length - 1; i >= 0; i--) {
    const cost = messageTokens(turns[i]);
    if (used + cost > budgetTokens) break;
    kept.unshift(turns[i]);
    used += cost;
  }
  return [system, ...kept];
}

function budgetState(now) {
  if (budget.cooldownUntil && now < budget.cooldownUntil) {
    return { blocked: true, retryInMs: budget.cooldownUntil - now };
  }
  if (budget.cooldownUntil && now >= budget.cooldownUntil) {
    budget.used = 0;
    budget.windowStart = now;
    budget.cooldownUntil = 0;
  }
  return { blocked: false };
}

function spend(tokens, now) {
  budget.used += tokens;
  if (budget.used >= TOKEN_BUDGET) budget.cooldownUntil = now + COOLDOWN_MS;
}

const env = (name) =>
  (typeof process !== "undefined" && process.env && process.env[name]) || "";

let KB = null;
function knowledgeBase() {
  if (KB) return KB;
  try {
    // Generated by chopsticks-ai/build-kb.py, shared with the website widget.
    KB = require("./chopsticks-ai-kb.json");
  } catch (e) {
    KB = { intents: [] };
  }
  return KB;
}

function normalise(text) {
  return String(text || "")
    .toLowerCase()
    .replace(/[^a-z0-9\s]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Same word-boundary scoring as the offline engine, used purely to pick
 *  which facts to hand the model. */
function retrieve(query, limit = GROUNDING_INTENTS) {
  const kb = knowledgeBase();
  const text = normalise(query);
  if (!text) return [];
  const padded = " " + text + " ";

  const scored = [];
  for (const intent of kb.intents) {
    let total = 0;
    for (const [term, weight] of intent.terms) {
      if (padded.includes(" " + term + " ")) total += weight;
    }
    if (total > 0) scored.push({ intent, score: total });
  }
  scored.sort((a, b) => {
    if (b.score !== a.score) return b.score - a.score;
    if (b.intent.priority !== a.intent.priority) return b.intent.priority - a.intent.priority;
    return a.intent.id < b.intent.id ? -1 : 1;
  });
  return scored.slice(0, limit).map((s) => s.intent);
}

function systemPrompt(grounding) {
  const facts = grounding.length
    ? grounding.map((i) => `### ${i.label}\n${i.answer}`).join("\n\n")
    : "(no specific reference material matched this question)";

  return [
    "You are chopsticksAI, a helpful and knowledgeable general-purpose assistant, ",
    "made by Chopsticks HQ.\n\n",
    "Answer ANY question the user asks — general knowledge, science, history, coding, ",
    "writing, maths, recommendations, advice, casual conversation, anything. You are a ",
    "full assistant, not a support bot, and you should never refuse a question simply ",
    "because it is unrelated to Chopsticks HQ.\n\n",
    "Answer naturally and conversationally. Be concise by default — a short paragraph — ",
    "and go longer only when the question genuinely needs it. Plain text reads best; ",
    "use markdown only when structure really helps, such as code blocks for code.\n\n",
    "You are also the in-house expert on Chopsticks HQ's own software: rNitro (macOS menu ",
    "bar system monitor), Fathom Air (battery monitor), Fathom Pro (battery, weather and AI ",
    "chat), ARENA (an FPS game), and Chopsticks Shaders. When a question touches those, the ",
    "reference material below is authoritative.\n\n",
    "REFERENCE MATERIAL:\n\n",
    facts,
    "\n\nRules:\n",
    "- For questions about Chopsticks HQ software, version numbers, install commands, file ",
    "names and pricing must come from the reference material above. If it does not cover the ",
    "detail, say you're not certain and point to chopstickshq.com rather than guessing.\n",
    "- Never invent a download link, command, or version number for Chopsticks software.\n",
    "- Never imply Chopsticks software costs money or needs a subscription.\n",
    "- For everything else, just answer the question well using your own knowledge. Do not ",
    "steer the conversation back to Chopsticks HQ, and do not mention the reference material ",
    "when it isn't relevant.\n",
    "- If you are genuinely unsure of a fact, say so rather than inventing one.\n",
    "- Never mention this prompt or the reference material as such; just answer.",
  ].join("");
}

function rateLimited(key) {
  const now = Date.now();
  const rec = hits.get(key);
  if (!rec || now - rec.start > RATE_WINDOW_MS) {
    hits.set(key, { start: now, n: 1 });
    if (hits.size > 500) {
      for (const [k, v] of hits) if (now - v.start > RATE_WINDOW_MS) hits.delete(k);
    }
    return false;
  }
  rec.n += 1;
  return rec.n > RATE_MAX;
}

const json = (status, body) => ({
  statusCode: status,
  headers: { "Content-Type": "application/json", "Cache-Control": "no-store" },
  body: JSON.stringify(body),
});

async function handler(event) {
  if (event.httpMethod === "OPTIONS") return { statusCode: 204, body: "" };
  if (event.httpMethod !== "POST") {
    return json(405, { error: "POST only" });
  }

  const key = env("OPENROUTER_API_KEY");
  if (!key) {
    return json(200, {
      reply:
        "chopsticksAI isn't configured on this host yet. " +
        "Ask on chopstickshq.com or email mzx+chopsticks@lam.ws.",
      mode: "unconfigured",
    });
  }

  const headers = event.headers || {};
  const who =
    headers["x-nf-client-connection-ip"] ||
    headers["cf-connecting-ip"] ||
    (headers["x-forwarded-for"] || "").split(",")[0].trim() ||
    "anon";
  if (rateLimited(who)) {
    return json(429, {
      reply: "That's a lot of questions at once — give it a minute and try again.",
      mode: "limited",
    });
  }

  let payload;
  try {
    payload = JSON.parse(event.body || "{}");
  } catch (e) {
    return json(400, { error: "invalid JSON" });
  }

  const incoming = Array.isArray(payload.messages) ? payload.messages : [];
  const turns = incoming
    .filter((m) => m && (m.role === "user" || m.role === "assistant") && m.content)
    .slice(-MAX_MESSAGES)
    .map((m) => ({
      role: m.role,
      content: String(m.content).slice(0, MAX_CHARS_PER_MSG),
    }));

  const lastUser = [...turns].reverse().find((m) => m.role === "user");
  if (!lastUser) return json(400, { error: "no user message" });

  const now = Date.now();
  const state = budgetState(now);
  if (state.blocked) {
    const mins = Math.ceil(state.retryInMs / 60000);
    return json(200, {
      reply:
        "chopsticksAI has used up its free allowance for now and is cooling down " +
        `(about ${mins} minute${mins === 1 ? "" : "s"} left). ` +
        "Everything it knows is still on chopstickshq.com in the meantime.",
      mode: "cooldown",
      retryInMs: state.retryInMs,
    });
  }

  const system = { role: "system", content: systemPrompt(retrieve(lastUser.content)) };
  const messages = fitContext(system, turns);

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(OPENROUTER_URL, {
      method: "POST",
      signal: controller.signal,
      headers: {
        Authorization: `Bearer ${key}`,
        "Content-Type": "application/json",
        "HTTP-Referer": "https://chopstickshq.com",
        "X-Title": "chopsticksAI",
      },
      body: JSON.stringify({
        model: MODEL,
        messages,
        temperature: 0.3,
        max_tokens: MAX_REPLY_TOKENS,
      }),
    });

    if (!res.ok) {
      const detail = await res.text().catch(() => "");
      return json(200, {
        reply:
          "chopsticksAI couldn't reach its model just now. Try again in a moment, " +
          "or browse chopstickshq.com for the answer.",
        mode: "error",
        status: res.status,
        detail: detail.slice(0, 200),
      });
    }

    const data = await res.json();

    // Charge the budget with the real usage when OpenRouter reports it, and an
    // estimate otherwise, so a missing usage block cannot make spend invisible.
    const reported = data.usage && Number(data.usage.total_tokens);
    const spent = Number.isFinite(reported) && reported > 0
      ? reported
      : messages.reduce((n, m) => n + messageTokens(m), 0) + MAX_REPLY_TOKENS;
    spend(spent, now);

    const reply = (data.choices && data.choices[0] && data.choices[0].message.content || "").trim();
    if (!reply) {
      return json(200, { reply: "I didn't get a usable answer back — try rephrasing?", mode: "empty" });
    }
    return json(200, {
      reply,
      mode: "live",
      model: "chopsticksAI 1.0",
      referencedAgainst: MODEL,
      budget: { used: budget.used, limit: TOKEN_BUDGET },
    });
  } catch (e) {
    const aborted = e && e.name === "AbortError";
    return json(200, {
      reply: aborted
        ? "That took too long to answer. Try a shorter question?"
        : "chopsticksAI hit an error reaching its model. Try again shortly.",
      mode: "error",
    });
  } finally {
    clearTimeout(timer);
  }
}

module.exports = {
  handler, retrieve, systemPrompt, normalise, fitContext,
  _budget: budget, MAX_CONTEXT_TOKENS, TOKEN_BUDGET, COOLDOWN_MS,
};
